research_task:
  description: >
    Conduct an advanced investigation into climate risk forecasting for {location}.
    Explore the latest scientific research, satellite-based observations, and predictive
    modeling techniques. Identify recent trends and anomalies in NDVI, NDMI, NDRI, and
    atmospheric variables that could signal emerging environmental risks such as droughts,
    floods, or wildfires. Incorporate insights from peer-reviewed studies, Earth observation
    platforms (e.g., MODIS, Sentinel, Landsat), and regional climate models, considering
    that the current year is {current_year}.
  expected_output: >
    A list of 10 bullet points summarizing the most significant scientific findings,
    datasets, and modeling approaches relevant to climate risk forecasting for {location}
    as of {date}. Each point should provide a concise but data-informed insight.
  agent: climate_researcher
  output_file: output/research_findings.md


reporting_task:
  description: >
    Review and synthesize all research and analytical outputs into a clear, well-structured
    report for decision-makers. Explain how geospatial indicators (NDVI, NDMI, NDRI)
    and meteorological trends contribute to the forecasted risks in {location} for {date}.
    Highlight key insights such as vegetation stress trends, soil moisture decline, or
    temperature anomalies that elevate climate hazard probabilities. Provide actionable
    interpretations and policy-relevant recommendations.
  expected_output: >
    A comprehensive markdown-formatted report that presents the forecast findings in
    natural language. The report should include an executive summary, methodology overview,
    detailed risk interpretation, and recommendations for local authorities or
    environmental planners.
  agent: climate_reporting_agent
  context:
    - research_task
  output_file: output/final_climate_risk_report.md
